export const USER_DETAILS = 'USER_DETAILS';

export const SET_COORDS = 'SET_COORDS';
export const SET_INTITIAL_POSITION = 'SET_INITIAL_POSITION';

export const SET_INFO_TOGGLE = 'SET_INFO_TOGGLE';
export const SET_CENTER_EN = 'SET_CENTER_EN';

export const SET_COMMUTER_TRAVEL_DATA = 'SET_COMMUTER_TRAVEL_DATA';
export const SET_DRIVER_TRAVEL_DATA = 'SET_DRIVER_TRAVEL_DATA';